#!/bin/bash
###### Системные функции #####


#Функция корректного влючения лимитов
function limits() {
NAME=${1}
BITE_LIMIT=${2}
IP=${3}

#Добавляем юзера в цепочку,если нет цепочки то создаем ее
if ! ipset -L ${NAME} &>/dev/null
then
#Цепочки нет, создаем
${IPSET} -N ${NAME} iphash
#Формируем правила. Разрешаем доступ между юзеркими сетями
${IPTABLES} -I FORWARD -m set --match-set ${NAME} src,dst -j ACCEPT
${IPTABLES} -I FORWARD -m ratelimit --ratelimit-set ${NAME}_download --ratelimit-mode src -j DROP
${IPTABLES} -I FORWARD -m ratelimit --ratelimit-set ${NAME}_upload --ratelimit-mode dst -j DROP
fi
#Добавляем IP в список IPSet
${IPSET} -A ${NAME} ${IP}
#Вшарашиваем лимиты в соотвествии с выбранным тарифом
if [ -f /proc/net/ipt_ratelimit/${NAME}_download ];then echo / > /proc/net/ipt_ratelimit/${NAME}_download; fi
if [ -f /proc/net/ipt_ratelimit/${NAME}_upload ];then echo / > /proc/net/ipt_ratelimit/${NAME}_upload; fi
IPS=`${IPSET} -L ${NAME} | sed '1,/Members/ d' | tr -s '\r\n' ',' | sed 's/.$//'`
#Скачка (Download)
echo @+${IPS} ${BITE_LIMIT} > /proc/net/ipt_ratelimit/${NAME}_download
#Загрузка (Upload)
echo @+${IPS} $((${BITE_LIMIT} / 2)) > /proc/net/ipt_ratelimit/${NAME}_upload
}


function check_d {
if ! [ -d ${1}/ ]; then
log_e "Дириктория ${1} не создана, создаем"
mkdir ${1}/
fi
}
function check_f {
if ! [ -f ${1} ]; then
log_e "Файла ${1} нет , создаем"
touch ${1}
fi
}


### Функции логирования
### Логгер
log() {
message="[ $(date +"%y-%m-%d %T") ] $@"
if ! [[ -z ${DEBUG} ]]; then echo "$message"; fi
echo $message >>$LOGFILE
}

log_e() {
message="[ $(date +"%y-%m-%d %T") ] [ ERROR ] $@"
if ! [[ -z ${DEBUG} ]]; then echo "$message"; fi
echo $message >>$LOGFILE
}
#Функция отчетов для пользователей
function reports {
USER_ID=$1 #ID Юзера для кого уведомление
TYPE=$2 #Тип уведомления
TITLE=$3 #Заголовок уведомления (ХЗ нужен ли)
DESC=$4 #Текст уведомления
mysql_one "INSERT INTO reports(user_id,type,title,description,created_at,updated_at) VALUES ('${USER_ID}', '${TYPE}','${TITLE}','${DESC}',NOW(),NOW());"
}


### MySQL функции
### Функция для перебора значений(Ответом будет массив)
function mysql_array {
if ${DB_MARIA} 
then
${MYSQL} --user=${DB_USER} --password=${DB_PASSWORD} --host=${DB_SERVER} --port=${DB_PORT} -sse "${1}" ${DB_NAME}
else 
${MYSQL} --login-path=${DB_PROFILE} -sse "${1}" ${DB_NAME}
fi
}
### Функция для получения или значения
function mysql_one {
if ${DB_MARIA} 
then
echo "${1}" | ${MYSQL} --user=${DB_USER} --password=${DB_PASSWORD} --host=${DB_SERVER} --port=${DB_PORT} -A -B -s ${DB_NAME}
else
echo "${1}" | ${MYSQL} --login-path=${DB_PROFILE} -A -B -s ${DB_NAME}
fi
}



